version: '2.1'
services:
  simple-go-prepaid-card:
    image: caevv/simple-go-prepaid-card
    environment:
      APP_LOG_LEVEL: "DEBUG"
    ports:
    - 8110:8080
    depends_on:
      card-db:
        condition: service_healthy

  card-db:
    image: postgres:10.2
    command: postgres -c log_statement=all
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
    - card-db-volume:/docker-entrypoint-initdb.d
    ports:
    - 5462:5432
    healthcheck:
      test    : [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout : 5s
      retries : 5

volumes:
  card-db-volume:
